name: Deploy to Workshop

on:
  push:
    branches: [ dev ]
  workflow_dispatch:    # Manual trigger (button in GitHub Actions tab)
  # Optional: auto-deploy on push to main branch
  # push:
  #   branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: vurv78/gmod-upload@master
        with:
          id: 3670751046          # Replace with YOUR workshop addon ID
          changelog: "Deployment via Github to latest changes"
        env:
          STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
          STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}